"use client";
/* eslint-disable @next/next/no-img-element -- local, volatile canvas previews */
import { useRef, useState, type PointerEvent } from "react";
import { QUESTIONS_PER_PAGE, TEMPLATE_VERSION, type PaperSurvey } from "@/modules/contracts";
import { COMMENT_REGION, HEIGHT, WIDTH, templateRows, templateSvg } from "@/modules/template";
import { detectMarks, type Point } from "@/modules/marks";
import { alignPhoto, downloadFile, svgCanvas } from "@/modules/images";

type Answer = { value: string; reviewed: boolean; note: string };
type Photo = { source: HTMLCanvasElement; hash: string; preview: string; corners: Point[]; aligned?: HTMLCanvasElement; alignedPreview?: string };
const cornerNames=["top-left (TL)","top-right (TR)","bottom-right (BR)","bottom-left (BL)"];
export function ImportWorkspace({surveys,reviewer}:{surveys:PaperSurvey[];reviewer:string}) {
  const [surveyId,setSurveyId]=useState(surveys[0]?.id??"");const survey=surveys.find(s=>s.id===surveyId);
  const [page,setPage]=useState(0);const [photos,setPhotos]=useState<Record<number,Photo>>({});const photo=photos[page];
  const [answers,setAnswers]=useState<Record<string,Answer>>({});const [overall,setOverall]=useState("");const [comment,setComment]=useState("");const [ocrDraft,setOcrDraft]=useState("");
  const [services,setServices]=useState<string[]>([]);const [visitType,setVisitType]=useState("");const [role,setRole]=useState("");const [locale,setLocale]=useState("en");
  const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [saved,setSaved]=useState<string|null>(null);const key=useRef<string|null>(null);
  if(!survey)return <section className="panel"><h2>No printable survey available</h2><p>Publish a survey with unconditional rating questions and English wording in the hospital Questions page. Printable prompts must be 160 characters or shorter.</p></section>;
  const pageCount=Math.ceil(survey.questions.length/QUESTIONS_PER_PAGE);const rows=templateRows(survey,page);const reviewed=survey.questions.filter(q=>answers[q.id]?.reviewed&&answers[q.id]!.value!=="").length;
  const ready=reviewed===survey.questions.length&&Array.from({length:pageCount},(_,i)=>photos[i]?.aligned).every(Boolean)&&services.length>0&&visitType&&role&&overall&&confirmed;
  function changeAnswer(id:string,value:string) {setAnswers(previous=>({...previous,[id]:{value,reviewed:false,note:"Edited manually"}}));setConfirmed(false);}
  function reset(id=surveyId) {setSurveyId(id);setPage(0);setPhotos({});setAnswers({});setOverall("");setComment("");setOcrDraft("");setServices([]);setVisitType("");setRole("");setConfirmed(false);setError("");setSaved(null);key.current=null;}
  async function printable() {setBusy("Preparing printable form…");setError("");try {const {jsPDF}=await import("jspdf");const pdf=new jsPDF({unit:"mm",format:"a4"});for(let i=0;i<pageCount;i++){if(i)pdf.addPage();const canvas=await svgCanvas(templateSvg(survey!,i));pdf.addImage(canvas.toDataURL("image/png"),"PNG",0,0,210,297);}downloadFile(pdf.output("blob"),`feedback-v${survey!.version}-${survey!.id}.pdf`);}catch{setError("Could not prepare the printable form.");}finally{setBusy("");}}
  async function upload(file:File) {
    setError("");if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>10*1024*1024){setError("Choose a JPEG, PNG or WebP image up to 10 MB.");return;}
    setBusy("Opening photograph…");const url=URL.createObjectURL(file);
    try {const image=new Image();image.src=url;await image.decode();if(image.naturalWidth*image.naturalHeight>40000000)throw new Error("Image too large");const scale=Math.min(1,1800/Math.max(image.naturalWidth,image.naturalHeight));const source=document.createElement("canvas");source.width=Math.round(image.naturalWidth*scale);source.height=Math.round(image.naturalHeight*scale);source.getContext("2d")!.drawImage(image,0,0,source.width,source.height);
      const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await file.arrayBuffer())),byte=>byte.toString(16).padStart(2,"0")).join("");
      setPhotos(prev=>({...prev,[page]:{source,hash,preview:source.toDataURL("image/jpeg",.85),corners:[]}}));setAnswers(prev=>{const copy={...prev};for(const row of rows)delete copy[row.id];return copy;});if(page===pageCount-1){setOverall("");setComment("");setOcrDraft("");}setConfirmed(false);key.current=null;
    }catch{setError("Could not read this image. Use a clear, smaller photograph.");}finally{URL.revokeObjectURL(url);setBusy("");}
  }
  function selectCorner(event:PointerEvent<HTMLDivElement>) {
    if(!photo||photo.corners.length===4||busy)return;const bounds=event.currentTarget.getBoundingClientRect();const point={x:(event.clientX-bounds.left)/bounds.width*photo.source.width,y:(event.clientY-bounds.top)/bounds.height*photo.source.height};setPhotos(prev=>({...prev,[page]:{...photo,corners:[...photo.corners,point]}}));
  }
  async function analyse() {if(!photo)return;setBusy("Aligning page and finding marks…");setError("");try {const blank=await svgCanvas(templateSvg(survey!,page)),aligned=alignPhoto(photo.source,photo.corners),reference=blank.getContext("2d")!.getImageData(0,0,WIDTH,HEIGHT),filled=aligned.getContext("2d")!.getImageData(0,0,WIDTH,HEIGHT);const next:Record<string,Answer>={};
      for(const row of rows){const detection=detectMarks(reference,filled,row.boxes);const value=detection.selected===null?"":detection.selected===5?"na":String(detection.selected+1);next[row.id]={value,reviewed:false,note:({suggested:"Suggested mark · review required",blank:"No mark found",ambiguous:"Multiple or unclear marks",faint:"Faint mark · choose manually"})[detection.state]};if(row.id==="overall")setOverall(value);}
      setAnswers(prev=>({...prev,...next}));setPhotos(prev=>({...prev,[page]:{...photo,aligned,alignedPreview:aligned.toDataURL("image/jpeg",.85)}}));setConfirmed(false);
    }catch(error){setError(error instanceof Error?error.message:"Could not align this page.");}finally{setBusy("");}}
  async function extractComment() {const last=photos[pageCount-1]?.aligned;if(!last)return;setBusy("Reading the comments area…");setError("");try {const crop=document.createElement("canvas");crop.width=COMMENT_REGION.width-12;crop.height=COMMENT_REGION.height-12;crop.getContext("2d")!.drawImage(last,COMMENT_REGION.x+6,COMMENT_REGION.y+6,crop.width,crop.height,0,0,crop.width,crop.height);const {createWorker}=await import("tesseract.js");const worker=await createWorker(({en:"eng",hi:"hin",mr:"mar"} as const)[locale as "en"|"hi"|"mr"]);try {const result=await worker.recognize(crop);setOcrDraft(result.data.text.slice(0,2000));}finally{await worker.terminate();}}catch{setError("Could not read the comments area. You can transcribe it manually.");}finally{setBusy("");}}
  async function save() {if(!ready)return;setBusy("Saving reviewed response…");setError("");key.current??=crypto.randomUUID();try {const response=await fetch("/api/imports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({surveyVersionId:survey!.id,templateVersion:TEMPLATE_VERSION,pageHashes:Array.from({length:pageCount},(_,i)=>photos[i]!.hash),idempotencyKey:key.current,locale,visitType,servicesUsed:services,respondentRole:role,overallRating:Number(overall),comment,confirmed:true,answers:survey!.questions.map(q=>({questionId:q.id,rating:answers[q.id]!.value==="na"?null:Number(answers[q.id]!.value),reviewed:answers[q.id]!.reviewed}))})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not save the response.");setSaved(result.replayed?"These photos were already imported. No second response was created.":"Reviewed response saved. It is now available in the hospital dashboard.");setPhotos({});setComment("");setOcrDraft("");setAnswers({});}catch(error){setError(error instanceof Error?error.message:"Could not save. Retry with the same photos.");}finally{setBusy("");}}
  if(saved)return <section className="panel success" role="status"><h2>Import complete</h2><p>{saved}</p><button onClick={()=>reset()}>Import another form</button></section>;
  return <><section className="panel intro"><div><span className="eyebrow">1 · Choose the paper form</span><h2>Published questionnaire</h2><p>Use the same version printed on the patient&apos;s form. Photos stay on this device; only approved answers are saved.</p></div><label>Survey version<select value={surveyId} disabled={Boolean(busy)} onChange={event=>reset(event.target.value)}>{surveys.map(s=><option key={s.id} value={s.id}>{s.hospital} · {s.title} · v{s.version}</option>)}</select></label><button className="secondary" disabled={Boolean(busy)} onClick={()=>void printable()}>Download printable PDF</button></section>
    <div className="import-grid"><section className="panel photo-panel"><div className="section-heading"><div><span className="eyebrow">2 · Photograph & align</span><h2>Paper form</h2></div><span className="badge">Page {page+1} of {pageCount}</span></div><label>Page<select value={page} disabled={Boolean(busy)} onChange={event=>{setPage(Number(event.target.value));setError("");}}>{Array.from({length:pageCount},(_,i)=><option key={i} value={i}>Page {i+1}{photos[i]?.aligned?" · aligned":""}</option>)}</select></label><label className="upload">Upload page {page+1}<input key={`${surveyId}-${page}`} type="file" accept="image/jpeg,image/png,image/webp" disabled={Boolean(busy)} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);}}/></label>
    {photo?<><p className="hint">{photo.corners.length<4?`Select the centre of the ${cornerNames[photo.corners.length]} cross on the photo.`:"Four corners selected. Align this page to find the marks."}</p><div className="photo" onPointerDown={selectCorner} role="img" aria-label="Photographed form; select the four printed corner crosses"><img src={photo.preview} alt="Photographed paper feedback" draggable={false}/>{photo.corners.map((point,i)=><span className="corner" key={i} style={{left:`${point.x/photo.source.width*100}%`,top:`${point.y/photo.source.height*100}%`}}>{i+1}</span>)}</div><div className="actions"><button disabled={Boolean(busy)||photo.corners.length!==4} onClick={()=>void analyse()}>Align & find marks</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>{setPhotos(prev=>({...prev,[page]:{...photo,corners:[],aligned:undefined,alignedPreview:undefined}}));setAnswers(prev=>{const copy={...prev};for(const row of rows)delete copy[row.id];return copy;});if(page===pageCount-1)setOverall("");setConfirmed(false);}}>Reset corners</button></div><details><summary>Enter corner positions with the keyboard</summary><div className="corner-inputs">{[0,1,2,3].map(i=><fieldset key={i}><legend>{cornerNames[i]}</legend>{(["x","y"] as const).map(axis=><label key={axis}>{axis.toUpperCase()} (%)<input type="number" min="0" max="100" step="0.1" disabled={Boolean(busy)} value={photo.corners[i]?Number((photo.corners[i]![axis]/(axis==="x"?photo.source.width:photo.source.height)*100).toFixed(1)):""} onChange={event=>{const points=[...photo.corners];while(points.length<4)points.push({x:0,y:0});points[i]={...points[i]!,[axis]:Number(event.target.value)/100*(axis==="x"?photo.source.width:photo.source.height)};setPhotos(prev=>({...prev,[page]:{...photo,corners:points,aligned:undefined,alignedPreview:undefined}}));setConfirmed(false);}}/></label>)}</fieldset>)}</div></details></>:<div className="empty"><strong>A clear photo makes review easier</strong><p>Include all four corner crosses. Use even light and keep the paper flat.</p></div>}</section>
    <section className="panel review-panel"><div className="section-heading"><div><span className="eyebrow">3 · Review every answer</span><h2>Detected responses</h2></div><span className="badge">{reviewed}/{survey.questions.length} reviewed</span></div><p className="hint">Suggestions are not final. Compare each crop with the paper and confirm it. Blank or unclear marks stay unresolved.</p>{rows.filter(row=>row.id!=="overall").map(row=>{const answer=answers[row.id];return <div className={`answer ${answer?.reviewed?"reviewed":""}`} key={row.id}><strong>{survey.questions.findIndex(q=>q.id===row.id)+1}. {row.prompt}</strong>{photo?.alignedPreview&&<div className="crop" style={{aspectRatio:"430 / 55",backgroundImage:`url(${photo.alignedPreview})`,backgroundSize:`${WIDTH/430*100}% auto`,backgroundPosition:`${548/(WIDTH-430)*100}% ${(row.boxes[0]!.y-5)/(HEIGHT-55)*100}%`}} role="img" aria-label={`Marked rating boxes for ${row.prompt}`}/>}<div className="answer-controls"><label>Selected answer<select value={answer?.value??""} disabled={Boolean(busy)} onChange={event=>changeAnswer(row.id,event.target.value)}><option value="">Unresolved</option>{survey.ratingLabels.map((label,i)=><option key={i} value={i+1}>{i+1} — {label}</option>)}<option value="na">Explicit N/A mark</option></select></label><label className="check"><input type="checkbox" disabled={Boolean(busy)||!answer?.value||!photo?.aligned} checked={answer?.reviewed??false} onChange={event=>{setAnswers(prev=>({...prev,[row.id]:{...prev[row.id]!,reviewed:event.target.checked}}));setConfirmed(false);}}/>Reviewed</label></div><p className="hint">{answer?.note??"Upload and align this page first."}</p></div>;})}</section></div>
    <section className="panel"><span className="eyebrow">4 · Complete the recorded details</span><h2>Response details</h2><p className="hint">Transcribe these from the paper or verified visit context. Do not infer them from a tick.</p><div className="details-grid"><label>Visit type<select value={visitType} disabled={Boolean(busy)} onChange={e=>{setVisitType(e.target.value);setConfirmed(false);}}><option value="">Select visit type</option>{survey.visitTypes.map(type=><option key={type}>{type}</option>)}</select></label><label>Completed by<select value={role} disabled={Boolean(busy)} onChange={e=>{setRole(e.target.value);setConfirmed(false);}}><option value="">Select respondent</option><option value="PATIENT">Patient</option><option value="CAREGIVER">Caregiver</option></select></label><label>Original response language<select value={locale} disabled={Boolean(busy)} onChange={e=>{setLocale(e.target.value);setConfirmed(false);}}><option value="en">English</option><option value="hi">Hindi</option><option value="mr">Marathi</option></select></label><label>Overall experience<select value={overall} disabled={Boolean(busy)} onChange={e=>{setOverall(e.target.value);setConfirmed(false);}}><option value="">Unresolved</option>{survey.ratingLabels.map((label,i)=><option key={i} value={i+1}>{i+1} — {label}</option>)}</select></label></div><fieldset className="services"><legend>Services used</legend>{survey.services.map(service=><label className="check" key={service.key}><input type="checkbox" disabled={Boolean(busy)} checked={services.includes(service.key)} onChange={e=>{setServices(prev=>e.target.checked?[...prev,service.key]:prev.filter(s=>s!==service.key));setConfirmed(false);}}/>{service.label}</label>)}</fieldset><label>Optional comment<textarea rows={4} maxLength={2000} disabled={Boolean(busy)} value={comment} onChange={e=>{setComment(e.target.value);setConfirmed(false);}}/></label><div className="actions"><button className="secondary" disabled={Boolean(busy)||!photos[pageCount-1]?.aligned} onClick={()=>void extractComment()}>Read comments with OCR</button><span className="hint">OCR runs locally. Handwriting may need manual transcription.</span></div>{ocrDraft&&<div className="ocr"><label>OCR draft — check before using<textarea value={ocrDraft} maxLength={2000} disabled={Boolean(busy)} onChange={e=>setOcrDraft(e.target.value)}/></label><button className="secondary" disabled={Boolean(busy)} onClick={()=>{setComment(ocrDraft);setConfirmed(false);}}>Use reviewed comment</button></div>}</section>
    <section className="panel save-panel"><div><h2>Save reviewed response</h2><p>Reviewed by {reviewer}. Scores will be calculated on the server and shown in the hospital dashboard.</p><label className="check"><input type="checkbox" disabled={Boolean(busy)} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the survey version, all page photos, every answer, overall rating and visit details against the paper.</label></div><button disabled={Boolean(busy)||!ready} onClick={()=>void save()}>Save to hospital records</button></section>{busy&&<p className="notice" role="status">{busy}</p>}{error&&<p className="notice error" role="alert">{error}</p>}</>;
}
